name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^5.0.0
  font_awesome_flutter: ^10.5.0
  google_maps_flutter: ^2.2.3
  timeline_tile: ^2.0.0
  intl: ^0.18.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # The assets section for your application
  assets:
    - assets/avatar.png
    
